### ISSUE TITLE
[Bug]: Autoshow Mods Don't Work

### ISSUE THREAD

**Issue by danger2k** [ForzaMods/AIO#138]
### What version of the aio were you running?

0.52

### Game

FH5

### Game Version

Steam

### What is the bug?

Autoshow "show all cars" and "free cars" doesn't work after the latest update, speed hacks and whatnot work so I know the mod menu works but the Autoshow mods are now patched.

**Comment by PX123444b** [comment]
True

**Comment by tranche2cake** [comment]
True

**Comment by lizardguts73** [comment]
I used the all cars in autoshow hack last season to get all the cars. Then i stopped playing the game for a few weeks only to come back to a ban. So anyone wanting to get all the cars you missed through this menu beaware you will most likely get banned.

**Comment by lmaobvobo** [comment]
thats actually not true. you get banned when your on a fresh account within the past few weeks because theres been a ban wave.

**Comment by lmaobvobo** [comment]
@danger2k once attatched in game check "all cars" and buy them from the car collection.

**Comment by lizardguts73** [comment]
@lmaobvobo It wasn't a fresh account its an account that I've had for years. I also know how to use the hacks since ive been using them for the past year as well. They added some sort of anti cheat that can detect when something is trying to mess with the games code. I've got a HWID ban and a Microsoft account ban now.
