### ISSUE TITLE
[Bug]: Can not run on Windows 11

### ISSUE THREAD

**Issue by MemeDealer0254** [ForzaMods/AIO#173]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Steam

### What is the bug?

The .exe file can not start on windows 11. Already tried run as admin but to no avail

**Comment by L0v3craft** [comment]
Same here on Windows 10 and I have installed also:

.NET 7.0 Desktop Runtime (v7.0.4)
.NET 7.0 Runtime (v7.0.4)
ASP.NET Core 7.0 Runtime (v7.0.4)

**Comment by retardgithubsuser** [comment]
same here
run on windows 11, but the AIO is not starting

**Comment by Friuuu** [comment]
Same issue, windows 10, AIO will not open. Event viewer suggests it is a .NET related error.

**Comment by coolgamerguy378** [comment]
Same here, on latest windows 11 no running at all, click application and it wont even start, at first run prompted for .net librarys which have been installed still no luck yet.

**Comment by coolgamerguy378** [comment]
More Info:

Application: Forza-Mods-AIO.exe
CoreCLR Version: 7.0.423.11508
.NET Version: 7.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.Exception: This assembly is protected by an unregistered version of Eziriz's ".NET Reactor"! This assembly won't further work.
   at Forza_Mods_AIO.Filter.PoolParserFilter.IncludeBase()
   at .cctor()
   --- End of inner exception stack trace ---

**Comment by Poll2512** [comment]
+1

**Comment by Dshez1** [comment]
+1

**Comment by Humwq** [comment]
+1

**Comment by blahpunk** [comment]
+1

**Comment by Friuuu** [comment]
This issue is **not** completed

**Comment by szaaamerik** [comment]
> This issue is **not** completed

The issue **is** completed because its **known** and will be fixed with a new **AIO Release**

**Comment by AJV009** [comment]
> More Info:
> 
> Application: Forza-Mods-AIO.exe CoreCLR Version: 7.0.423.11508 .NET Version: 7.0.4 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeInitializationException: The type initializer for '' threw an exception. ---> System.Exception: This assembly is protected by an unregistered version of Eziriz's ".NET Reactor"! This assembly won't further work. at Forza_Mods_AIO.Filter.PoolParserFilter.IncludeBase() at .cctor() --- End of inner exception stack trace ---

same issues as shown here!
